# =============== 0. Run-Variable =============
# The run-identifier is used as name for output directories where all samples are bundled together
# i.e. OUTRIDER, FRASER
global_variable:
  run_identifier: "tutorial_run"

# =============== 1.) Switch variables =============

# **Important**:
# 1. Submodule 0 has to be run separately at the end, when all summary files are available.
# 2. Submodule 1 has to be run first alone, as the output of this submodule is
# used as input for the other submodules. Subsequently, the other modules can be run in (almost) any order.

module_switches:
  # ------- 1.0 Module: Report Generation ---------
  run_module0_report_generation: False

  # ------- 1.1 Module: Quality-Control, Preprocessing, and Alignment --------
  run_module1_qc_preprocessing_and_alignment: True

  # ------- 1.2 Module: Detection of gene fusion events ---------
  run_module2_gene_fusion_detection: True
  
  # ------- 1.3 Module: Detection and Quantification of gene products (transcripts) and analysis ---------
  run_module3_gene_expression_quantification_and_analysis: False

  # ------- 1.4 Module: Splicing Patterns Analysis ---------
  run_module4_splicing_pattern_analysis: False

   # ------- 1.5 Module: Variant calling based on RNAseq via GATK-workflow ---------
  run_module5_variant_calling_based_on_rna_seq: False

  # ------- 1.6 Module: ncRNA Analysis ---------
  run_module6_ncRNA_analysis: False


# =============== 2. Module output directory names =================
module_output_dir_names:
  output_dir_module0_report_generation:
    "output/module0_report_generation"
  output_dir_module1_qc_preprocessing_and_alignment:
    "output/module1_qc_preproc_and_alignment"
  output_dir_module2_gene_fusion_detection:
    "output/module2_gene_fusion_detection"
  output_dir_module3_gene_expression_quantification_and_analysis:
    "output/module3_gene_expression_quantification_and_analysis"
  output_dir_module4_splicing_patterns_analysis:
    "output/module4_splicing_patterns_analysis"
  output_dir_module5_variant_calling:
    "output/module5_variant_calling"
  output_dir_module6_ncRNA_analysis:
    "output/module6_ncRNA_analysis"
