# =============== Configuration file for module: QualityControl, Preprocessing, and Alignment =============
# Use this config-file to switch on/off the features that you need for your personal research.
# Furthermore, you can set the detailed parameters for the respective features.


# =============== 1.) Primary settings =============

# ------- 1.1 Module: Quality-Control, Preprocessing, and Alignment --------
module1_qc_preprocessing_and_alignment_settings:
  switch_variables:
    # Switch variables to decide which features are to be included
    run_check_of_strandedness: True      # Run python script to check strandedness of input read files
    run_trimmomatic: True                # Run trimmomatic: Quality trimming of input reads
    run_kraken2: True                    # Run Kraken2: Check for potential contamination via Kraken2
    run_fastqc_before_trimming: True      # Run fastqc: Quality control of input reads before trimming
    run_fastqc_after_trimming: True       # Run fastqc: Quality control of input reads after trimming
    run_alignment:
      use_star: True                     # Run STAR alignment: Align reads to reference genome
      use_olego: False                    # Run Olego alignment: Align reads to reference genome
    run_bamstats: True                  # Run bamstats: Quality control of aligned reads
    run_qualimap: True                   # Run Qualimap: Quality control of alignment results
    run_deeptools: False                  # Run deeptools: Quality control of alignment results
    run_multiqc: True                     # Run multiqc: Summarize all quality control results into one output-file

  # =============== 1.2 Output directories =============
  # The output directories for the respective tool-outputs are defined here.
  # This is important for importing the outputs into the GUI
  output_directories:
    bamstats_output_dir: "bamstats"
    check_strandedness_output_dir: "check_strandedness"
    fastqc_output_dir: "fastqc"
    kraken2_output_dir: "kraken2"
    multiqc_output_dir: "multiqc"
    qualimap_output_dir: "qualimap"
    deeptools_output_dir: "deeptools"

    # DO NOT CHANGE: This directories are hardcoded into the main_helpers for accessibility in all modules
    # TODO: Move this to main configuration file?!
    olego_output_dir: "olego"
    star_output_dir: "star"
    trimmomatic_output_dir: "trimmomatic"


  # =============== 2. Required settings & input files for selected functionalities =============
  # ATTENTION: Use absolute paths when defining input file paths!

  # 2.1 Check of strandedness
  check_strandedness_settings:
    # Nothing

  # 2.2 Trimming of reads
  trimmomatic_settings:
    quality_score_encoding:
      "phred33"    # "phred64" or "phred33" or "unknown"

  # 2.3 Kraken2: Check for potential contamination via Kraken2
  kraken2_settings:
    # Dir of Kraken2 database, if empty, then miniKraken2-db will be downloaded
    # Should include file: taxo.k2d
    file_kraken2_db:
      # "/sc-projects/sc-proj-btg/olik_splicing_project/input_data/Kraken2_dbs/minikraken2_v1_8GB_201904"
    
    # Download link for Kraken2 database, if empty, then miniKraken2-db will be downloaded
    kraken_db_download_link:
      "https://genome-idx.s3.amazonaws.com/kraken/minikraken2_v2_8GB_201904.tgz"

  # 2.4 FastQC
  fastqc_settings:
    # Nothing

  # 2.5 Alignments
  alignment_settings:
    # 2.5.1 STAR alignment: Align reads to reference genome
    star_alignment_settings:
      # Reference genome sequence file, that is used to create the STAR index
      reference_genome_build:
        "GRCh38_chr21"          # "GRCh37" or "GRCh38" or "GRCh38_chr21" (for testing purposes)

      index_build:
        sjdbOverhang:
          "99"              # recommended by leafcutter authors -> wrapper takes it
        extra_settings:
          ""                # additional flags for STAR index generation

      alignment:
        # Detailed settings for STAR alignment
        # -outSAMstrandField intronMotif command is to add XS strand tags to spliced reads (removes the ones with unknown strand)
        # twopassMode: "Basic"        ->  allows to detect more spliced reads mapping to novel junctions
        # chimeric read alignments are included and marked!
        # BAM is unsorted, but will be sorted later
        # '>-' indicates a YAML multi-line Block Scalar without newline at the end
        extra_settings: >-
          --quantMode GeneCounts 
          --outSAMstrandField intronMotif 
          --outSAMtype BAM Unsorted 
          --twopassMode Basic 
          --chimSegmentMin 10 --chimOutType WithinBAM SoftClip 
          --chimJunctionOverhangMin 10 --chimScoreMin 1 --chimScoreDropMax 30 
          --chimScoreJunctionNonGTAG 0 --chimScoreSeparation 1 --alignSJstitchMismatchNmax 5 -1 5 5 
          --chimSegmentReadGapMax 3

        # extract splice junctions from this file and use them to greatly improve accuracy of the mapping
        use_sjdb_file: True

    # 2.5.2 Olego alignment: Align reads to reference genome
    olego_alignment_settings:
      # If Olego is requested: Provide a path, where either
      # 1.) a subdirectory "olego" is located, which contains the Olego executable and the Olego index
      # 2.) no subdirectory "olego" is located, so that the workflow will install Olego and build the index
      olego_installation_dir:
        # "/sc-scratch/sc-scratch-btg/olik_splicing_project/splice-prediction/snakemake_workflows/Snakemake_Main/lib"
        "/Users/oliverkuchler/Studium/Master_BioInfo_Berlin/Masterthesis/Topic_Splicing_Variants/splice-prediction/snakemake_workflows/Snakemake_Main/lib"

      # Reference genome sequence file, that is used to create the Olego index
      reference_genome_fasta_file:
        # "/sc-projects/sc-proj-btg/olik_splicing_project/input_data/reference_genome/hg19_analysis_set/hg19.p13.plusMT.no_alt_analysis_set.fa"
        "/Users/oliverkuchler/Studium/Master_BioInfo_Berlin/Masterthesis/Topic_Splicing_Variants/splice-prediction/snakemake_workflows/Snakemake_Main/local_test/reference_genomes/ncbi_sourced/hg19.p13.plusMT.no_alt_analysis_set.fa"

      # If empty: Olego will be downloaded and installed automatically
      # Regression model for Olego, if empty then default model will be used: olego/models/hg.cfg
      olego_regression_model:
        # "/sc-scratch/sc-scratch-btg/olik_splicing_project/splice-prediction/snakemake_workflows/Snakemake_Main/lib/olego/models/hg.cfg"     # Regression model for Olego
        "/Users/oliverkuchler/Studium/Master_BioInfo_Berlin/Masterthesis/Topic_Splicing_Variants/splice-prediction/snakemake_workflows/Snakemake_Main/lib/olego/models/hg.cfg"     # Regression model for Olego

      olego_allowed_missmatches:      # Allowed nr of mismatches for aligning
        4
      olego_min_exon_size:            # Minimal length of exon (read-fragments)
        6                             # leafcutter authors suggest: 6

  # 2.6 DeepTools: Analysis of read coverage of genomic regions
  deeptools_settings:
    min_map_quality:              # Minimal mapping quality of reads
      30
    region:           # Region of interest for read coverage analysis
      # Can be empty, then the whole genome will be analyzed
      # "chr1:1000000-2000000"      # Format: "chr1:1000000-2000000"

  # 2.7 QualiMap: Quality assessment of alignment via qualimap
  qualimap_settings:
    qualimap_java_heap_size:        # Java heap size for qualimap
      "6G"
      # "131G"

  # 2.8 MultiQC: Summarize all quality control results into one output-file
  multiqc_settings:
    # Nothing
