site_name: SnakeSplice

theme:
  name: material
  logo: img/logo/with_eyes2_2.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - toc.follow

    # Code blocks
    - content.code.copy

  # set colors
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: "teal"
      accent: "teal"

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: "teal"
      accent: "teal"

  # set font
  font:
    text: "Roboto"
    code: "Roboto Mono"

# Extensions for code blocks
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition        # Adds admonition blocks
  - pymdownx.details

# Navigation
nav:
  - Home: index.md
  - "Getting started": 
    - "Installation": getting_started/installation.md
    - "Tutorial - Data set up": getting_started/tutorial_data.md
    - "Tutorial - QC & Alignment": getting_started/tutorial_alignments.md
    - "Tutorial - Gene Fusion Events": getting_started/tutorial_gene_fusions.md
    - "Tutorial - Gene Expression": getting_started/tutorial_gene_expression.md
    - "Tutorial - Splicing": getting_started/tutorial_splicing.md
    - "Tutorial - Generate Reports": getting_started/tutorial_report_generation.md
  - "Pipeline Content":
    - "Overview": pipeline_content/overview.md
    - "Result Summary": pipeline_content/overall_summary.md
    - "QC & Alignmemt": pipeline_content/qc_alignment.md
    - "Gene Fusions": pipeline_content/gene_fusions.md
    - "Gene Expression": pipeline_content/gene_expression.md
    - "Splicing": pipeline_content/splicing.md
  - About: about.md

